// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteGitHubToken() {
  return window['go']['main']['App']['DeleteGitHubToken']();
}

export function GetCIStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCIStatus'](arg1, arg2, arg3);
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetGitHubToken() {
  return window['go']['main']['App']['GetGitHubToken']();
}

export function GetPullRequests(arg1, arg2) {
  return window['go']['main']['App']['GetPullRequests'](arg1, arg2);
}

export function GetRepos() {
  return window['go']['main']['App']['GetRepos']();
}

export function SaveGitHubToken(arg1) {
  return window['go']['main']['App']['SaveGitHubToken'](arg1);
}
