// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {provider} from '../models';
import {main} from '../models';

export function DeleteGitHubToken():Promise<void>;

export function GetCIStatus(arg1:string,arg2:string,arg3:string):Promise<provider.CIStatus>;

export function GetDashboardData():Promise<main.DashboardData>;

export function GetGitHubToken():Promise<boolean>;

export function GetPullRequests(arg1:string,arg2:string):Promise<Array<provider.PullRequest>>;

export function GetRepos():Promise<Array<provider.Repo>>;

export function SaveGitHubToken(arg1:string):Promise<void>;
